name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_fonts: ^5.0.0 


flutter:
  uses-material-design: true

  assets:
    - assets/img/entrada.png
    - assets/img/comidaBrasileira.png
    - assets/img/comidaFrancesa.png
    - assets/img/comidaItaliana.png
    - assets/img/comidaJaponesa.png
    - assets/img/popularChurrascaria.png
    - assets/img/usuarioConfig.png
    - assets/img/mahai.png
    - assets/img/laBelleCusine.png
    - assets/img/teroBrasa.png
    - assets/img/pepe.png
    - assets/img/FotoAvaliacaoTeroBrasa.png
    - assets/img/AnaClara.png
    - assets/img/Pedro.png
    - assets/img/Marco.png
    - assets/img/Mapa.png

